type: ephemeral
deck_name: "eph-padding-1k-c2-100k"
scale: 0.75
client_padding_budget: [1000, 2000]
client_blocking_budget: [0, 0]
client_padding_frac: [0.95, 0.95]
client_blocking_frac: [0.0, 0.0]
server_padding_budget: [1000, 3000]
server_blocking_budget: [0, 0]
server_padding_frac: [0.95, 0.95]
server_blocking_frac: [0.0, 0.0]
n_train_machines: 50_000
n_valid_machines: 5_000
n_test_machines: 5_000
fixed_per_trace: false
