type: front
padding_budget_max_client: 6000
padding_budget_max_server: 6000
window_min_client: 5.0
window_min_server: 5.0
window_max_client: 12.0
window_max_server: 12.0
num_states_client: 1
num_states_server: 1
n_train_machines: 50_000
n_valid_machines: 4_000
n_test_machines: 4_000
fixed_per_trace: false

